spring.application.name=loan-management
# Datasource settings
spring.datasource.url=jdbc:mysql://localhost:3306/loan_management
spring.datasource.username=root
spring.datasource.password=add your own
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Hibernate properties
spring.jpa.properties.hibernate.format_sql=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
server.port=7718


management.health.resilience4j.circuitbreaker.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.resilience4j.circuitbreaker.show-details=always


# Circuit Breaker Settings
resilience4j.circuitbreaker.instances.customer.slidingWindowSize=10
resilience4j.circuitbreaker.instances.customer.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.customer.failureRateThreshold=50
resilience4j.circuitbreaker.instances.customer.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.customer.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.customer.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.customer.slowCallDurationThreshold=2000
resilience4j.circuitbreaker.instances.customer.slowCallRateThreshold=70
resilience4j.circuitbreaker.instances.customer.automaticTransitionFromOpenToHalfOpenEnabled=true

# Retry Settings
resilience4j.retry.instances.customer.maxAttempts=3
resilience4j.retry.instances.customer.waitDuration=2000
resilience4j.retry.instances.customer.exponentialBackoffMultiplier=2.0
resilience4j.retry.instances.customer.retryExceptions=java.io.IOException,java.net.SocketTimeoutException
resilience4j.retry.instances.customer.ignoreExceptions=java.lang.IllegalArgumentException

# Rate Limiter Settings
resilience4j.ratelimiter.instances.customer.limitForPeriod=10
resilience4j.ratelimiter.instances.customer.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.customer.timeoutDuration=500ms

# Bulkhead Settings
resilience4j.bulkhead.instances.customer.maxConcurrentCalls=25
resilience4j.bulkhead.instances.customer.maxWaitDuration=0

# Time Limiter Settings
resilience4j.timelimiter.instances.customer.timeoutDuration=3s
resilience4j.timelimiter.instances.customer.cancelRunningFuture=true

